### ISSUE TITLE
`.start()` panics on Linux

### ISSUE THREAD

**Issue by samuela** [TheNeikos/spinner#20]
I just tried taking a project that runs fine on my macOS machine and running it on Ubuntu 18.10 (recompiled on the new machine). I got a relatively nasty panic:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0:     0x55b82e7fbb53 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hf8722b0178fb1b63
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x55b82e7f65b8 - std::sys_common::backtrace::_print::hc40139e5f1d656ee
                               at src/libstd/sys_common/backtrace.rs:70
   2:     0x55b82e7f9802 - std::panicking::default_hook::{{closure}}::h993d43465919c16a
                               at src/libstd/sys_common/backtrace.rs:58
                               at src/libstd/panicking.rs:200
   3:     0x55b82e7f9574 - std::panicking::default_hook::h73d2c2ec3d9ba5a4
                               at src/libstd/panicking.rs:215
   4:     0x55b82e7f9f10 - std::panicking::rust_panic_with_hook::h744417edfe714d72
                               at src/libstd/panicking.rs:478
   5:     0x55b82e7f9a91 - std::panicking::continue_panic_fmt::h3557b3c3fa21b47b
                               at src/libstd/panicking.rs:385
   6:     0x55b82e7f9975 - rust_begin_unwind
                               at src/libstd/panicking.rs:312
   7:     0x55b82e81726c - core::panicking::panic_fmt::h74ee8034b317ceed
                               at src/libcore/panicking.rs:85
   8:     0x55b82e81719b - core::panicking::panic::h13421bef49a1c627
                               at src/libcore/panicking.rs:49
   9:     0x55b82de53364 - <core::option::Option<T>>::unwrap::hf740564626465cd0
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:10
  10:     0x55b82de4b159 - spinner::Spinner::start::{{closure}}::h3ba9e9ea7cd8f9b8
                               at /home/darthvader/.cargo/registry/src/github.com-1ecc6299db9ec823/spinner-0.4.0/src/lib.rs:155
  11:     0x55b82de562af - std::sys_common::backtrace::__rust_begin_short_backtrace::h51f62df944680da3
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/sys_common/backtrace.rs:135
  12:     0x55b82de4d4c2 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hd44f4311b81c9e03
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/thread/mod.rs:469
  13:     0x55b82de58505 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd9dd17becad4e09a
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/panic.rs:309
  14:     0x55b82de58779 - std::panicking::try::do_call::h95fce4d911f840ca
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/panicking.rs:297
  15:     0x55b82e803629 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:92
  16:     0x55b82de5865f - std::panicking::try::h38d89abf56305788
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/panicking.rs:276
  17:     0x55b82de585a5 - std::panic::catch_unwind::hc5fafb02ba7b953c
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/panic.rs:388
  18:     0x55b82de4d2a5 - std::thread::Builder::spawn_unchecked::{{closure}}::h54dad12197eba18a
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/thread/mod.rs:468
  19:     0x55b82de4db1c - <F as alloc::boxed::FnBox<A>>::call_box::h8fee3e86d6715bd9
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/boxed.rs:734
  20:     0x55b82e8029ed - std::sys::unix::thread::Thread::new::thread_start::h6fb76bcf544b6181
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/boxed.rs:744
                               at src/libstd/sys_common/thread.rs:14
                               at src/libstd/sys/unix/thread.rs:81
  21:     0x7f47100ff163 - start_thread
  22:     0x7f4710592dee - __clone
  23:                0x0 - <unknown>
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0:     0x55b82e7fbb53 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hf8722b0178fb1b63
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x55b82e7f65b8 - std::sys_common::backtrace::_print::hc40139e5f1d656ee
                               at src/libstd/sys_common/backtrace.rs:70
   2:     0x55b82e7f9802 - std::panicking::default_hook::{{closure}}::h993d43465919c16a
                               at src/libstd/sys_common/backtrace.rs:58
                               at src/libstd/panicking.rs:200
   3:     0x55b82e7f9574 - std::panicking::default_hook::h73d2c2ec3d9ba5a4
                               at src/libstd/panicking.rs:215
   4:     0x55b82e7f9f10 - std::panicking::rust_panic_with_hook::h744417edfe714d72
                               at src/libstd/panicking.rs:478
   5:     0x55b82e7f9a91 - std::panicking::continue_panic_fmt::h3557b3c3fa21b47b
                               at src/libstd/panicking.rs:385
   6:     0x55b82e7f9975 - rust_begin_unwind
                               at src/libstd/panicking.rs:312
   7:     0x55b82e81726c - core::panicking::panic_fmt::h74ee8034b317ceed
                               at src/libcore/panicking.rs:85
   8:     0x55b82e81719b - core::panicking::panic::h13421bef49a1c627
                               at src/libcore/panicking.rs:49
   9:     0x55b82de53364 - <core::option::Option<T>>::unwrap::hf740564626465cd0
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:10
  10:     0x55b82de4b159 - spinner::Spinner::start::{{closure}}::h3ba9e9ea7cd8f9b8
                               at /home/darthvader/.cargo/registry/src/github.com-1ecc6299db9ec823/spinner-0.4.0/src/lib.rs:155
  11:     0x55b82de562af - std::sys_common::backtrace::__rust_begin_short_backtrace::h51f62df944680da3
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/sys_common/backtrace.rs:135
  12:     0x55b82de4d4c2 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hd44f4311b81c9e03
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/thread/mod.rs:469
  13:     0x55b82de58505 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd9dd17becad4e09a
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/panic.rs:309
  14:     0x55b82de58779 - std::panicking::try::do_call::h95fce4d911f840ca
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/panicking.rs:297
  15:     0x55b82e803629 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:92
  16:     0x55b82de5865f - std::panicking::try::h38d89abf56305788
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/panicking.rs:276
  17:     0x55b82de585a5 - std::panic::catch_unwind::hc5fafb02ba7b953c
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/panic.rs:388
  18:     0x55b82de4d2a5 - std::thread::Builder::spawn_unchecked::{{closure}}::h54dad12197eba18a
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/thread/mod.rs:468
  19:     0x55b82de4db1c - <F as alloc::boxed::FnBox<A>>::call_box::h8fee3e86d6715bd9
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/boxed.rs:734
  20:     0x55b82e8029ed - std::sys::unix::thread::Thread::new::thread_start::h6fb76bcf544b6181
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/boxed.rs:744
                               at src/libstd/sys_common/thread.rs:14
                               at src/libstd/sys/unix/thread.rs:81
  21:     0x7f47100ff163 - start_thread
  22:     0x7f4710592dee - __clone
  23:                0x0 - <unknown>
```
It's panicking on this line: https://github.com/TheNeikos/spinner/blob/master/src/lib.rs#L155. After a bit of debugging I've found that exact line actually runs just fine on the main thread; it's just not working in the spinner thread. Therefore I'm guessing the fix should just be putting the terminal capture onto the main thread and then moving it into the closure.

**Comment by io12** [comment]
I can reproduce this

**Comment by io12** [comment]
This can be fixed by updating `term` to 0.6.1

**Comment by io12** [comment]
I made a PR to fix it

**Comment by io12** [comment]
This issue should be good to close after a new crates.io release

**Comment by TheNeikos** [comment]
Alright, it's out :smile:  https://crates.io/crates/spinner/0.5.0
