### ISSUE TITLE
bug: panicks in windows

### ISSUE THREAD

**Issue by kegesch** [TheNeikos/spinner#22]
The `spiner.start()` method panicks in windows at line [164 in `lib.rs`](https://github.com/TheNeikos/spinner/blob/ae9d25cb4690d5e17978db12fac7663156f2690f/src/lib.rs#L164).
The `Result` should probably be handled.

**Comment by TheNeikos** [comment]
Thanks for the bug report! Sadly I don't have a windows dev machine to explore this further. But if you (or someone) else feels like it, I'd gladly incorporate patches.

**Comment by Kab1r** [comment]
### Same issue in `x86_64-unknown-linux-musl`
Backtrace:
```csharp
thread '<unnamed>' panicked at 'called `Result::unwrap.'called `Result::unwrap()` on an `Err` value: NotSupported', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/spinner-0.5.0/src/lib.rs:164:17
stack backtrace:
   0:           0x7e23b4 - backtrace::backtrace::libunwind::trace::h234d741a55b60f88
   at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:           0x7e23b4 - backtrace::backtrace::trace_unsynchronized::h350b2c8c65b00d1d
   at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:           0x7e23b4 - std::sys_common::backtrace::_print_fmt::h4a536ea1c8e8e74a
   at src/libstd/sys_common/backtrace.rs:78
   3:           0x7e23b4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::had63074188e24509
   at src/libstd/sys_common/backtrace.rs:59
   4:           0x822fbc - core::fmt::write::h0f3ca38b916f7bdd
   at src/libcore/fmt/mod.rs:1069
   5:           0x7dc263 - std::io::Write::write_fmt::h904ea4dad7931404
   at src/libstd/io/mod.rs:1504
   6:           0x7e4b95 - std::sys_common::backtrace::_print::h5b567d4903ca6eb3
   at src/libstd/sys_common/backtrace.rs:62
   7:           0x7e4b95 - std::sys_common::backtrace::print::hf98b9b1b18a4dc81
   at src/libstd/sys_common/backtrace.rs:49
   8:           0x7e4b95 - std::panicking::default_hook::{{closure}}::h5fbf8e21242992f2
   at src/libstd/panicking.rs:198
   9:           0x7e48d2 - std::panicking::default_hook::hb4d89e36502020cd
   at src/libstd/panicking.rs:218
  10:           0x7e51f2 - std::panicking::rust_panic_with_hook::hc36f90fb81cc1268
   at src/libstd/panicking.rs:511
  11:           0x7e4ddb - rust_begin_unwind
   at src/libstd/panicking.rs:419
  12:           0x821731 - core::panicking::panic_fmt::h31cb4ec4ac5347b3
   at src/libcore/panicking.rs:111
  13:           0x821553 - core::option::expect_none_failed::h3e3ee4886fcb0833
   at src/libcore/option.rs:1268
  14:           0x43612a - std::sys_common::backtrace::__rust_begin_short_backtrace::h4fd314038fe1f508
  15:           0x437720 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he65dea6ba09ead6b
  16:           0x7e749a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7791eef1c6f45098
   at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  17:           0x7e749a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd7ef21d55fcbd5c6
   at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  18:           0x7e749a - std::sys::unix::thread::Thread::new::thread_start::he4cd09b6f7a97324
   at src/libstd/sys/unix/thread.rs:87
```
